# FreeBSD documentation

baseURL = "localhost"
title = "FreeBSD Documentation Portal"
copyright = "BSD 2-clause 'Simplified' License"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
disablePathToLower = true
theme = "beastie"
disableKinds = [ "taxonomy", "term", "RSS", "sitemap", "robotsTXT", "404" ]
authors = [ "carlavilla@FreeBSD.org" ]
ignoreFiles = [ "chapters-order.adoc$", "toc.adoc$", "toc-tables.adoc$", "toc-figures.adoc$", "toc-examples.adoc$", "toc-1.adoc$", "toc-2.adoc$", "toc-3.adoc$", "toc-4.adoc$", "toc-5.adoc$", "chapter.adoc$", "contrib-386bsd.adoc$", "contrib-additional.adoc$", "contrib-committers.adoc$", "contrib-corealumni.adoc$", "contrib-develalumni.adoc$", "contrib-develinmemoriam.adoc$", "contrib-portmgralumni.adoc$", "books.adoc$", "\\.po$" ]
enableRobotsTXT = true

[params]
  websiteURL = "https://www.FreeBSD.org/"
  description = "FreeBSD Documentation Portal"
  isOnline = false

[markup.asciidocExt]
    preserveTOC = true
    extensions = ["man-macro", "inter-document-references-macro", "cross-document-references-macro", "sectnumoffset-treeprocessor", "packages-macro", "git-macro"]
    [markup.asciidocExt.attributes]
      env-beastie = true
      isOnline = false
      skip-front-matter = true

[outputs]
home = [ "HTML" ]
page = [ "HTML" ]
list = [ "HTML" ]
single = [ "HTML" ]
section = [ "HTML" ]
