# FreeBSD documentation

baseURL = "https://docs.freebsd.org/"
title = "FreeBSD Documentation Portal"
copyright = "BSD 2-clause 'Simplified' License"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
disablePathToLower = true
theme = "beastie"
disableKinds = [ "taxonomy", "taxonomyTerm" ]
authors = [ "carlavilla@FreeBSD.org" ]
ignoreFiles = [ "chapter.adoc$", "contrib-386bsd.adoc$", "contrib-additional.adoc$", "contrib-committers.adoc$", "contrib-corealumni.adoc$", "contrib-develalumni.adoc$", "contrib-develinmemoriam.adoc$", "contrib-portmgralumni.adoc$", "\\.po$" ]
enableRobotsTXT = true
googleAnalytics = 'UA-22767463-1'

[params]
  websiteURL = "https://www.FreeBSD.org/"
  description = "FreeBSD Documentation Portal"
  isOnline = true

[markup.asciidocExt]
    extensions = ["man-macro", "inter-document-references-macro", "cross-document-references-macro", "sectnumoffset-treeprocessor", "packages-macro", "git-macro"]
    [markup.asciidocExt.attributes]
      env-beastie = true
      isOnline = true
      skip-front-matter = true

[outputs]
home = [ "HTML" ]
page = [ "HTML" ]
list = [ "HTML" ]
single = [ "HTML" ]
section = [ "HTML" ]
