# FreeBSD website

baseURL = "https://www.freebsd.org/"
title = "The FreeBSD Project"
copyright = "BSD 2-clause 'Simplified' License"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
theme = "beastie"
disableKinds = [ "taxonomy", "taxonomyTerm" ]
disableLanguages = ["tr", "el"]
disablePathToLower = true
authors = [ "carlavilla@FreeBSD.org" ]
ignoreFiles = [ "report-sample.md$" ]
enableRobotsTXT = true

preserveTOC = true

[markup.asciidocExt]
    preserveTOC = true
    extensions = ["man-macro", "inter-document-references-macro", "sectnumoffset-treeprocessor", "packages-macro", "git-macro"]

staticDir = ["static", "shared"]

[outputs]
home = [ "HTML" ]
page = [ "HTML" ]
list = [ "HTML" ]
single = [ "HTML" ]
section = [ "HTML", "RSS" ]

[outputFormats]
[outputFormats.Calendar]
BaseName = "calendar"
IsHTML = true
IsPlainText = false

[outputFormats.RSS]
MediaType = "application/rss+xml"
BaseName = "feed"
IsHTML = true
IsPlainText = false
noUgly = true
Rel = "alternate"
