---
name: Main
on:
  pull_request:
  push:
    branches:
      - main
      - valeaction

jobs:
  deploy:
    name: Lint doc
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: valeaction
      - name: Lint
        uses: errata-ai/vale-action@reviewdog
